Fix libvirt terraform tfvars example (#985)
On terraform 0.12, the extra `ha_updates` attribute will cause
`terraform apply` to fail with:

  Error: Duplicate object attribute

Remove the superfluous declaration and just use the 15-SP1 updates repo.